import { CardInterface } from '@/game/interfaces/card-interface';
import { CharacterTypeEnum } from '@/game/enums/character-type-enum';
import { ColorEnum } from '@/game/enums/color-enum';
import { defineStore } from 'pinia';
import { ref } from 'vue';

export const useCardStore = defineStore('cards', () => {
  const cards = ref<CardInterface[]>([]);
  function setCards(newCards: CardInterface[]) {
    cards.value = newCards;
  }
  function setData() {
    cards.value = dataCard;
  }
  function filterByColors(colors: ColorEnum[]): CardInterface[] {
    return cards.value.filter(card => colors.includes(card.color));
  }
  function searchByTerm(searchTerm: string, colors: ColorEnum[] = []): CardInterface[] {
    const lowerCaseTerm = searchTerm.toLowerCase();
    const filteredByColor = colors.length > 0 ? filterByColors(colors) : cards.value;
    return filteredByColor.filter(card => card.name.toLowerCase().includes(lowerCaseTerm));
  }
  return { cards, setCards, setData, filterByColors, searchByTerm };
});

export const dataCard: CardInterface[] = [
  {
    id: 1,
    name: 'Monkey. D. Luffy',
    image: 'ST01-001',
    descriptionPt:
      '[Ativar: Principal] [Uma vez por turno] Dê a este Líder ou até 1 dos seus Personagens descansado 1 carta DON!!.',
    descriptionEn:
      '[Activate: Main] [Once Per Turn] Give this Leader or up to 1 of your Characters 1 rested DON!! card.',
    characterType: CharacterTypeEnum.Leader,
    color: ColorEnum.Red,
  },
  {
    id: 2,
    name: 'Usopp',
    image: 'ST01-002',
    descriptionPt:
      '[DON!! X2] [Ao Atacar] Seu oponente não pode ativar um Personagem [Bloqueador] que tenha 5000 ou mais de Poder durante esta batalha. [Gatilho] Jogue esta carta.',
    descriptionEn:
      '[DON!! X2] [When Attacking] Your opponent cannot activate a [Blocker] Character that has 5000 or more Power during this battle. [Trigger] Play this card.',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Red,
  },
  {
    id: 3,
    name: '',
    image: 'ST01-003',
    descriptionPt: null,
    descriptionEn: null,
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Red,
  },
  {
    id: 4,
    name: '',
    image: 'ST01-004',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Red,
  },
  {
    id: 5,
    name: '',
    image: 'ST01-005',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Red,
  },
  {
    id: 6,
    name: '',
    image: 'ST01-006',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Red,
  },
  {
    id: 7,
    name: '',
    image: 'ST01-007',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Red,
  },
  {
    id: 8,
    name: '',
    image: 'ST01-008',
    descriptionPt: null,
    descriptionEn: null,
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Red,
  },
  {
    id: 9,
    name: '',
    image: 'ST01-009',
    descriptionPt: null,
    descriptionEn: null,
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Red,
  },
  {
    id: 10,
    name: '',
    image: 'ST01-010',
    descriptionPt: null,
    descriptionEn: null,
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Red,
  },
  {
    id: 11,
    name: '',
    image: 'ST01-011',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Red,
  },
  {
    id: 12,
    name: '',
    image: 'ST01-012',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Red,
  },
  {
    id: 13,
    name: '',
    image: 'ST01-013',
    descriptionPt: null,
    descriptionEn: null,
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Red,
  },
  {
    id: 14,
    name: '',
    image: 'ST01-014',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Event,
    color: ColorEnum.Red,
  },
  {
    id: 15,
    name: '',
    image: 'ST01-015',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Event,
    color: ColorEnum.Red,
  },
  {
    id: 16,
    name: '',
    image: 'ST01-016',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Event,
    color: ColorEnum.Red,
  },
  {
    id: 17,
    name: '',
    image: 'ST01-017',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Stage,
    color: ColorEnum.Red,
  },
  {
    id: 18,
    name: '',
    image: 'ST02-001',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 19,
    name: '',
    image: 'ST02-002',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 20,
    name: '',
    image: 'ST02-003',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 21,
    name: '',
    image: 'ST02-004',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 22,
    name: '',
    image: 'ST02-005',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 23,
    name: '',
    image: 'ST02-006',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 24,
    name: '',
    image: 'ST02-007',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 25,
    name: '',
    image: 'ST02-008',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 26,
    name: '',
    image: 'ST02-009',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 27,
    name: '',
    image: 'ST02-010',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 28,
    name: '',
    image: 'ST02-011',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 29,
    name: '',
    image: 'ST02-012',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 30,
    name: '',
    image: 'ST02-013',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 31,
    name: '',
    image: 'ST02-014',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 32,
    name: '',
    image: 'ST02-015',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 33,
    name: '',
    image: 'ST02-016',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 34,
    name: '',
    image: 'ST02-017',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Green,
  },
  {
    id: 35,
    name: '',
    image: 'ST03-001',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 36,
    name: '',
    image: 'ST03-002',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 37,
    name: '',
    image: 'ST03-003',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 38,
    name: '',
    image: 'ST03-004',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 39,
    name: '',
    image: 'ST03-005',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 40,
    name: '',
    image: 'ST03-006',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 41,
    name: '',
    image: 'ST03-007',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 42,
    name: '',
    image: 'ST03-008',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 43,
    name: '',
    image: 'ST03-009',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 44,
    name: '',
    image: 'ST03-010',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 45,
    name: '',
    image: 'ST03-011',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 46,
    name: '',
    image: 'ST03-012',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 47,
    name: '',
    image: 'ST03-013',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 48,
    name: '',
    image: 'ST03-014',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 49,
    name: '',
    image: 'ST03-015',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 50,
    name: '',
    image: 'ST03-016',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 51,
    name: '',
    image: 'ST03-017',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Blue,
  },
  {
    id: 52,
    name: '',
    image: 'ST04-001',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 53,
    name: '',
    image: 'ST04-002',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 54,
    name: '',
    image: 'ST04-003',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 55,
    name: '',
    image: 'ST04-004',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 56,
    name: '',
    image: 'ST04-005',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 57,
    name: '',
    image: 'ST04-006',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 58,
    name: '',
    image: 'ST04-007',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 59,
    name: '',
    image: 'ST04-008',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 60,
    name: '',
    image: 'ST04-009',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 61,
    name: '',
    image: 'ST04-010',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 62,
    name: '',
    image: 'ST04-011',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 63,
    name: '',
    image: 'ST04-012',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 64,
    name: '',
    image: 'ST04-013',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 65,
    name: '',
    image: 'ST04-014',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 66,
    name: '',
    image: 'ST04-015',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 67,
    name: '',
    image: 'ST04-016',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
  {
    id: 68,
    name: '',
    image: 'ST04-017',
    descriptionPt: '',
    descriptionEn: '',
    characterType: CharacterTypeEnum.Character,
    color: ColorEnum.Purple,
  },
];
